# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}\nuget

jobs:
  release:
    runs-on: windows-latest
    environment: "Production"
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: "5.x"

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11

      - name: Install msbuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install Nuget
        uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: "5.x"

      - name: Restore NuGet packages
        run: nuget restore FxMediator.sln
        working-directory: src

      - name: Build Client (Release)
        run: msbuild /t:restore /t:build /p:Configuration=Release /p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }} FxMediator.Client\FxMediator.Client.csproj
        working-directory: src

      - name: Pack Client (Release)
        run: nuget pack FxMediator.Client\FxMediator.Client.csproj -Properties Configuration=Release -OutputDirectory ${{ env.NuGetDirectory }}\client -Version ${{ steps.gitversion.outputs.NuGetVersionV2 }}
        working-directory: src

      - name: Pack Server (Release)
        run: dotnet pack FxMediator.Server\FxMediator.Server.csproj --configuration Release --output ${{ env.NuGetDirectory }}\server /p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }}
        working-directory: src

      - name: List files in nuget\client directory
        run: dir ${{ env.NuGetDirectory }}\client

      - name: Push Client to NuGet (Release)
        run: dotnet nuget push ${{ env.NuGetDirectory }}\client\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Push Server to NuGet (Release)
        run: dotnet nuget push ${{ env.NuGetDirectory }}\server\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Tag repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag -a v${{ steps.gitversion.outputs.NuGetVersionV2 }} -m "Release v${{ steps.gitversion.outputs.NuGetVersionV2 }}"
          git push https://${{ secrets.GITHUB_PAT }}@github.com/lfshr/FxMediator.git --tags
